[theme]
base = "dark"
primaryColor = "#00c7b7"
backgroundColor = "#0f1422"
secondaryBackgroundColor = "#171f32"
textColor = "#eef2fa"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
