[theme]
base = "light"
primaryColor = "#ee3a27"
backgroundColor = "#f9f8f3"
secondaryBackgroundColor = "#eeede8"
textColor = "#1a1a1a"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
